# Generated by Django 4.1.5 on 2023-01-30 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(4)]),
        ),
    ]
