# Generated by Django 4.1.5 on 2023-01-31 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_address_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Postcode'),
        ),
    ]
