# Generated by Django 4.1.5 on 2023-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.IntegerField(blank=True, default=0, verbose_name='Postcode'),
        ),
    ]
