# Generated by Django 4.1.5 on 2023-02-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0006_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shopping_cart',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
