# Generated by Django 4.1.5 on 2023-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0007_profile_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='shopping_cart',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
