# Generated by Django 4.1.5 on 2023-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_shoppingcart_product_remove_shoppingcart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default_product.png', null=True, upload_to='', verbose_name='Product Photos'),
        ),
    ]
