# Generated by Django 4.1.5 on 2023-02-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
