# Generated by Django 4.1.5 on 2023-02-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_new_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_price',
            new_name='old_price',
        ),
    ]
