# Generated by Django 4.1.5 on 2023-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_new_price_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_item',
            field=models.IntegerField(default=1),
        ),
    ]
